### ISSUE TITLE
ids에 aladin.co.kr이 없는 경우 에러가 난다.

### ISSUE THREAD

**Issue by sseeookk** [sseeookk/Calibre-Aladin.co.kr-Metadata-Source-Plugin#14]
책을 선택하면
어떤것은 에러가 안나지만
몇개만 대화상자가 귀찮게 뜬다.
옆의 디테일 정보 창에 아무것도 나오지 않는다.
이런 에러가 나고 있다.

calibre, version 2.77.0
ERROR: Unhandled exception: <b>TypeError</b>:expected string or buffer

calibre 2.77 Portable embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: KyoboBook (0, 2, 0) && Open With (1, 5, 10) && Reading List (1, 6, 6) && food network Recipe Reader (1, 0, 2) && Recipe Reader (1, 0, 1) && EpubMerge (2, 1, 0) && Alternativeto.net (0, 4, 0) && Aladin.co.kr (0, 2, 3) && Find Duplicates (1, 6, 2)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\book_details.py", line 758, in show_data
  File "site-packages\calibre\gui2\book_details.py", line 523, in show_data
  File "site-packages\calibre\gui2\book_details.py", line 53, in render_html
  File "site-packages\calibre\gui2\book_details.py", line 130, in render_data
  File "site-packages\calibre\ebooks\metadata\book\render.py", line 174, in mi_to_html
  File "site-packages\calibre\init.py", line 638, in prepare_string_for_xml
TypeError: expected string or buffer

이것저것 살펴보니
Basic metadata에서
아예 ids의 내용을 지우면 
위 에러가 나지 않는다.

예)
변신이야기 1
에러 난다
isbn:9788937460012, kyobobook:9788937460012
에러 안난다. 왜지? 웃기다.
isbn:9788937460012, aladin.co.kr:60482, kyobobook:9788937460012

aladin.co.kr: 이 꼭 있어야 한다.
아니면 아예 아무것도 없던지...

**Comment by sseeookk** [comment]
에러 수정 : ids에 aladin.co.kr이 없는 경우 에러가 난다. #14
