### ISSUE TITLE
플러그인이 동작하지 않습니다.

### ISSUE THREAD

**Issue by limjdsn** [sseeookk/Calibre-Aladin.co.kr-Metadata-Source-Plugin#22]
안녕하세요? 덕분에 잘 사용하고 있습니다.

어느 순간부터 검색결과가 이상하게 나와서 살펴보니 알라딘 플러그인이 전혀 작동하지 않고 있었습니다.
저번과는 다르게 플러그인 설치는 정상적으로 되는 것으로 보아, 알라딘 사이트에 무슨 변화가 있어서 그런 것이 아닌가 추측해 봅니다.

==========================================
calibre, version 6.14.1
ERROR: No matches found: <p>Failed to find any books that match your search. Try making the search <b>less specific</b>. For example, use only the author's last name and a single distinctive word from the title.<p>To see the full log, click "Show details".

Running identify query with parameters: 
{'title': '디즈니 기묘한 소원 5 : 가짜 초대장', 'authors': ['베라 스트레인지'], 'identifiers': {}, 'timeout': 30} 
Using plugins: Aladin.co.kr (1, 0, 1) 
The log from individual plugins is below 

****************************** Aladin.co.kr (1, 0, 1) ****************************** 
Found 0 results 
Downloading from Aladin.co.kr took 4.3311028480529785 
Querying: http://www.aladin.co.kr/search/wsearchresult.aspx?SearchTarget=All&SearchWord=%EB%94%94%EC%A6%88%EB%8B%88+%EA%B8%B0%EB%AC%98%ED%95%9C+%EC%86%8C%EC%9B%90+5+%EB%B2%A0%EB%9D%BC+%EC%8A%A4%ED%8A%B8%EB%A0%88%EC%9D%B8%EC%A7%80
Failed to make identify query: 'http://www.aladin.co.kr/search/wsearchresult.aspx?SearchTarget=All&SearchWord=%EB%94%94%EC%A6%88%EB%8B%88+%EA%B8%B0%EB%AC%98%ED%95%9C+%EC%86%8C%EC%9B%90+5+%EB%B2%A0%EB%9D%BC+%EC%8A%A4%ED%8A%B8%EB%A0%88%EC%9D%B8%EC%A7%80'
Traceback (most recent call last):
  File "calibre_plugins.aladin_co_kr.config", line 19, in <module>
    from PyQt4 import QtGui
ModuleNotFoundError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.aladin_co_kr.__init__", line 222, in identify
    self._parse_search_results(log, title, authors, root, matches, timeout)
  File "calibre_plugins.aladin_co_kr.__init__", line 339, in _parse_search_results
    import calibre_plugins.aladin_co_kr.config as cfg
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.aladin_co_kr.config", line 23, in <module>
    from PyQt5 import Qt as QtGui
ImportError: cannot import name 'Qt' from 'qt' (/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/qt/__init__.pyc) 

******************************************************************************** 
The identify phase took 4.46 seconds 
The longest time (4.331103) was taken by: Aladin.co.kr 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
=========================================

한 번 확인해 주시기를 부탁드립니다. 
항상 감사드립니다.

**Comment by limjdsn** [comment]
교보 플러그인도 함께 작동하지 않는 것이, 알라딘이나 교보 사이트의 문제가 아니라 캘리버에서 뭔가 바뀐 것일 수도 있겠다 생각이 드네요. 알라딘과 교보가 동시에 뭔가를 바꿨을 가능성도 있긴 하겠습니다만. ^^;
