### ISSUE TITLE
ImportError가 뜹니다

### ISSUE THREAD

**Issue by hotsixman** [sseeookk/Calibre-Aladin.co.kr-Metadata-Source-Plugin#23]
calibre, version 7.4.0
에러: 처리되지 않은 예외상황: <b>ImportError</b>:cannot import name 'Qt' from 'qt' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\qt\__init__.pyc)

calibre 7.4  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: ko
Successfully initialized third party plugins: Aladin.co.kr (1, 0, 1)
Traceback (most recent call last):
  File "calibre_plugins.aladin_co_kr.config", line 19, in <module>
ModuleNotFoundError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 298, in double_clicked
  File "calibre\gui2\preferences\plugins.py", line 378, in modify_plugin
  File "calibre\customize\__init__.py", line 163, in do_user_config
  File "calibre_plugins.aladin_co_kr.__init__", line 74, in config_widget
  File "calibre\customize\zipplugin.py", line 207, in exec_module
  File "calibre_plugins.aladin_co_kr.config", line 23, in <module>
ImportError: cannot import name 'Qt' from 'qt' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\qt\__init__.pyc)

**Comment by janghw4** [comment]
Pull request 참조하세요
